compile_dijkstra:
	g++ dijkstra.cpp -o dijkstra && ./dijkstra <shortest_path.txt

compile_bellman_ford:
	g++ bellman_ford.cpp -o bellman && ./bellman <shortest_path.txt

compile_kruskal:
	g++ kruskal.cpp -o kruskal && ./kruskal <mst_input.txt

compile_prim:
	g++ prim.cpp -o prim && ./prim <mst_input.txt
